export interface Paczkomat {
  code: string;
  address: string;
  city: string;
  hours: string;
}

export const paczkomaty: Paczkomat[] = [
     // TORUŃ
  { code: "TOR001", address: "ul. Kopernika 12 (Biedronka, Stare Miasto)", city: "Toruń", hours: "24/7" },
  { code: "TOR002", address: "ul. Mickiewicza 18", city: "Toruń", hours: "24/7" },
  { code: "TOR003", address: "ul. Żeglarska 5", city: "Toruń", hours: "24/7" },
  { code: "TOR004", address: "ul. Dąbrowskiego 8 (Lidl)", city: "Toruń", hours: "06:00-22:00" },
  { code: "TOR005", address: "ul. Olsztyńska 12 (Na Skarpie)", city: "Toruń", hours: "24/7" },
  { code: "TOR006", address: "ul. Rubinkowska 48 (Rubinkowo I)", city: "Toruń", hours: "24/7" },
  { code: "TOR007", address: "ul. Łódzka 72 (Mokre)", city: "Toruń", hours: "24/7" },
  { code: "TOR008", address: "ul. Gagarina 145 (Bielany)", city: "Toruń", hours: "24/7" },
  { code: "TOR009", address: "ul. Jarowa 8", city: "Toruń", hours: "24/7" },
  { code: "TOR010", address: "ul. Wrzosowa 12 (Wrzosy)", city: "Toruń", hours: "24/7" },
  { code: "TOR011", address: "ul. Chełmińska 95", city: "Toruń", hours: "24/7" },
  { code: "TOR012", address: "ul. Bydgoska 165", city: "Toruń", hours: "24/7" },
  { code: "TOR013", address: "ul. Reja 15 (Nowe Miasto)", city: "Toruń", hours: "24/7" },
  { code: "TOR014", address: "ul. Broniewskiego 22 (Jar)", city: "Toruń", hours: "24/7" },
  { code: "TOR015", address: "ul. Skarpowa 18 (Na Skarpie)", city: "Toruń", hours: "24/7" },
  { code: "TOR016", address: "ul. Rubinkowska 78 (Rubinkowo II)", city: "Toruń", hours: "24/7" },
  { code: "TOR017", address: "ul. Mokre 15", city: "Toruń", hours: "24/7" },
  { code: "TOR018", address: "ul. Koniuchy 25", city: "Toruń", hours: "24/7" },
  { code: "TOR019", address: "ul. Watzenrodego 8 (Rubinkowo I)", city: "Toruń", hours: "24/7" },
  { code: "TOR020", address: "ul. Rydygiera 33 (Rubinkowo II)", city: "Toruń", hours: "24/7" },
  { code: "TOR021", address: "ul. Skłodowskiej-Curie 25", city: "Toruń", hours: "24/7" },
  { code: "TOR022", address: "ul. Legionów 65", city: "Toruń", hours: "24/7" },
  { code: "TOR023", address: "ul. Olsztyńska 58", city: "Toruń", hours: "24/7" },
  { code: "TOR024", address: "ul. Łódzka 95", city: "Toruń", hours: "24/7" },
  { code: "TOR025", address: "ul. PCK 55 (Mokre)", city: "Toruń", hours: "24/7" },
  { code: "TOR026", address: "ul. Szubińska 12", city: "Toruń", hours: "24/7" },
  { code: "TOR027", address: "ul. Wschodnia 45", city: "Toruń", hours: "24/7" },
  { code: "TOR028", address: "ul. Chrobrego 33", city: "Toruń", hours: "24/7" },
  { code: "TOR029", address: "ul. Piłsudskiego 88", city: "Toruń", hours: "24/7" },
  { code: "TOR030", address: "ul. Sienkiewicza 22", city: "Toruń", hours: "24/7" },
  { code: "TOR031", address: "ul. Szubińska 45 (Biedronka)", city: "Toruń", hours: "24/7" },
  { code: "TOR032", address: "ul. Wschodnia 67", city: "Toruń", hours: "24/7" },
  { code: "TOR033", address: "ul. Chrobrego 12", city: "Toruń", hours: "24/7" },
  { code: "TOR034", address: "ul. Piłsudskiego 105", city: "Toruń", hours: "24/7" },
  { code: "TOR035", address: "ul. Sienkiewicza 88 (Nowe Miasto)", city: "Toruń", hours: "24/7" },
  { code: "TOR036", address: "ul. Kościuszki 55", city: "Toruń", hours: "24/7" },
  { code: "TOR037", address: "ul. Matejki 22", city: "Toruń", hours: "24/7" },
  { code: "TOR038", address: "ul. Kraszewskiego 18", city: "Toruń", hours: "24/7" },
  { code: "TOR039", address: "ul. Słowackiego 45", city: "Toruń", hours: "24/7" },
  { code: "TOR040", address: "ul. Norwida 12 (Rubinkowo)", city: "Toruń", hours: "24/7" },
  { code: "TOR041", address: "ul. Gałczyńskiego 33", city: "Toruń", hours: "24/7" },
  { code: "TOR042", address: "ul. Staffa 19", city: "Toruń", hours: "24/7" },
  { code: "TOR043", address: "ul. Tuwima 28", city: "Toruń", hours: "24/7" },
  { code: "TOR044", address: "ul. Lelewela 7 (Mokre)", city: "Toruń", hours: "24/7" },
  { code: "TOR045", address: "ul. Fredry 52", city: "Toruń", hours: "24/7" },
  { code: "TOR046", address: "ul. Asnyka 11", city: "Toruń", hours: "24/7" },
  { code: "TOR047", address: "ul. Konopnickiej 39 (Na Skarpie)", city: "Toruń", hours: "24/7" },
  { code: "TOR048", address: "ul. Reymonta 24", city: "Toruń", hours: "24/7" },
  { code: "TOR049", address: "ul. Żeromskiego 81", city: "Toruń", hours: "24/7" },
  { code: "TOR050", address: "ul. Wyspiańskiego 16", city: "Toruń", hours: "24/7" },
  { code: "TOR051", address: "ul. Tetmajera 9 (Bielany)", city: "Toruń", hours: "24/7" },
  { code: "TOR052", address: "ul. Kasprowicza 44", city: "Toruń", hours: "24/7" },
  { code: "TOR053", address: "ul. Słowackiego 120", city: "Toruń", hours: "24/7" },
  { code: "TOR054", address: "ul. Mickiewicza 95", city: "Toruń", hours: "24/7" },
  { code: "TOR055", address: "ul. Kopernika 68", city: "Toruń", hours: "24/7" },
  { code: "TOR056", address: "ul. Mostowa 12", city: "Toruń", hours: "24/7" },
  { code: "TOR057", address: "ul. Św. Józefa 33", city: "Toruń", hours: "24/7" },
  { code: "TOR058", address: "ul. Grunwaldzka 110", city: "Toruń", hours: "24/7" },
  { code: "TOR059", address: "ul. Wileńska 25", city: "Toruń", hours: "24/7" },
  { code: "TOR060", address: "ul. Lubicka 48", city: "Toruń", hours: "24/7" },
  { code: "TOR061", address: "ul. Bażyńskiego 19 (Rubinkowo II)", city: "Toruń", hours: "24/7" },
  { code: "TOR062", address: "ul. Dekerta 7", city: "Toruń", hours: "24/7" },
  { code: "TOR063", address: "ul. Popiełuszki 12", city: "Toruń", hours: "24/7" },
  { code: "TOR064", address: "ul. Bema 55", city: "Toruń", hours: "24/7" },
  { code: "TOR065", address: "ul. 1 Maja 88", city: "Toruń", hours: "24/7" },
  { code: "TOR066", address: "ul. Hallera 22", city: "Toruń", hours: "24/7" },
  { code: "TOR067", address: "ul. Czerwonej Armii 15", city: "Toruń", hours: "24/7" },
  { code: "TOR068", address: "ul. Kleeberga 9", city: "Toruń", hours: "24/7" },
  { code: "TOR069", address: "ul. Andersa 34", city: "Toruń", hours: "24/7" },
  { code: "TOR070", address: "ul. Czartoryskiego 18", city: "Toruń", hours: "24/7" },
  { code: "TOR071", address: "ul. Sobieskiego 67", city: "Toruń", hours: "24/7" },
  { code: "TOR072", address: "ul. Traugutta 29", city: "Toruń", hours: "24/7" },
  { code: "TOR073", address: "ul. Kościuszki 120", city: "Toruń", hours: "24/7" },
  { code: "TOR074", address: "ul. Matejki 45", city: "Toruń", hours: "24/7" },
  { code: "TOR075", address: "ul. Krasińskiego 8", city: "Toruń", hours: "24/7" },
  { code: "TOR076", address: "ul. Słowackiego 150", city: "Toruń", hours: "24/7" },
  { code: "TOR077", address: "ul. Wybickiego 33", city: "Toruń", hours: "24/7" },
  { code: "TOR078", address: "ul. Malczewskiego 12", city: "Toruń", hours: "24/7" },
  { code: "TOR079", address: "ul. Modrzewskiego 55", city: "Toruń", hours: "24/7" },
  { code: "TOR080", address: "ul. Elbląska 22", city: "Toruń", hours: "24/7" },
  { code: "TOR081", address: "ul. Sobieskiego 45 (Rubinkowo)", city: "Toruń", hours: "24/7" },
  { code: "TOR082", address: "ul. Traugutta 78", city: "Toruń", hours: "24/7" },
  { code: "TOR083", address: "ul. Kościuszki 145 (Mokre)", city: "Toruń", hours: "24/7" },
  { code: "TOR084", address: "ul. Matejki 67", city: "Toruń", hours: "24/7" },
  { code: "TOR085", address: "ul. Krasińskiego 33", city: "Toruń", hours: "24/7" },
  { code: "TOR086", address: "ul. Konopnickiej 90", city: "Toruń", hours: "24/7" },
  { code: "TOR087", address: "ul. Reymonta 55", city: "Toruń", hours: "24/7" },
  { code: "TOR088", address: "ul. Staffa 22", city: "Toruń", hours: "24/7" },
  { code: "TOR089", address: "ul. Tuwima 44", city: "Toruń", hours: "24/7" },
  { code: "TOR090", address: "ul. Gałczyńskiego 19", city: "Toruń", hours: "24/7" },
  { code: "TOR091", address: "ul. Norwida 67", city: "Toruń", hours: "24/7" },
  { code: "TOR092", address: "ul. Asnyka 12", city: "Toruń", hours: "24/7" },
  { code: "TOR093", address: "ul. Fredry 88", city: "Toruń", hours: "24/7" },
  { code: "TOR094", address: "ul. Malczewskiego 33", city: "Toruń", hours: "24/7" },
  { code: "TOR095", address: "ul. Wybickiego 55", city: "Toruń", hours: "24/7" },
  { code: "TOR096", address: "ul. Modrzewiowa 19", city: "Toruń", hours: "24/7" },
  { code: "TOR097", address: "ul. Rekreacyjna 78", city: "Toruń", hours: "24/7" },
  { code: "TOR098", address: "ul. Bajeczna 22", city: "Toruń", hours: "24/7" },
  { code: "TOR099", address: "ul. Czerkaska 67", city: "Toruń", hours: "24/7" },
  { code: "TOR100", address: "ul. Smukalska 44", city: "Toruń", hours: "24/7" },
  { code: "TOR101", address: "ul. Rycerska 19", city: "Toruń", hours: "24/7" },
  { code: "TOR102", address: "ul. Andersa 120", city: "Toruń", hours: "24/7" },
  { code: "TOR103", address: "ul. Sikorskiego 78", city: "Toruń", hours: "24/7" },
  { code: "TOR104", address: "ul. Maczka 33", city: "Toruń", hours: "24/7" },
  { code: "TOR105", address: "ul. Hallera 55", city: "Toruń", hours: "24/7" },
  { code: "TOR106", address: "ul. Dowbora-Muśnickiego 12", city: "Toruń", hours: "24/7" },
  { code: "TOR107", address: "ul. 11 Listopada 145", city: "Toruń", hours: "24/7" },
  { code: "TOR108", address: "ul. Piłsudskiego 88", city: "Toruń", hours: "24/7" },
  { code: "TOR109", address: "ul. Dworcowa 67", city: "Toruń", hours: "24/7" },
  { code: "TOR110", address: "ul. Pomorska 190", city: "Toruń", hours: "24/7" },
  { code: "TOR111", address: "ul. Kościuszki 120", city: "Toruń", hours: "24/7" },
  { code: "TOR112", address: "ul. Matejki 45", city: "Toruń", hours: "24/7" },
  { code: "TOR113", address: "ul. Mickiewicza 105", city: "Toruń", hours: "24/7" },
  { code: "TOR114", address: "ul. Sienkiewicza 78", city: "Toruń", hours: "24/7" },
  { code: "TOR115", address: "ul. Słowackiego 90", city: "Toruń", hours: "24/7" },
  { code: "TOR116", address: "ul. Krasińskiego 44", city: "Toruń", hours: "24/7" },
  { code: "TOR117", address: "ul. Konopnickiej 19", city: "Toruń", hours: "24/7" },
  { code: "TOR118", address: "ul. Reymonta 55", city: "Toruń", hours: "24/7" },
  { code: "TOR119", address: "ul. Staffa 33", city: "Toruń", hours: "24/7" },
  { code: "TOR120", address: "ul. Tuwima 78", city: "Toruń", hours: "24/7" },
  { code: "TOR121", address: "ul. Gałczyńskiego 22", city: "Toruń", hours: "24/7" },
  { code: "TOR122", address: "ul. Norwida 67", city: "Toruń", hours: "24/7" },
  { code: "TOR123", address: "ul. Asnyka 44", city: "Toruń", hours: "24/7" },
  { code: "TOR124", address: "ul. Fredry 19", city: "Toruń", hours: "24/7" },
  { code: "TOR125", address: "ul. Malczewskiego 88", city: "Toruń", hours: "24/7" },
  { code: "TOR126", address: "ul. Wybickiego 55", city: "Toruń", hours: "24/7" },
  { code: "TOR127", address: "ul. Modrzewiowa 33", city: "Toruń", hours: "24/7" },
  { code: "TOR128", address: "ul. Rekreacyjna 67", city: "Toruń", hours: "24/7" },
  { code: "TOR129", address: "ul. Bajeczna 12", city: "Toruń", hours: "24/7" },
  { code: "TOR130", address: "ul. Czerkaska 78", city: "Toruń", hours: "24/7" },
  { code: "TOR131", address: "ul. Smukalska 44", city: "Toruń", hours: "24/7" },
  { code: "TOR132", address: "ul. Rycerska 19", city: "Toruń", hours: "24/7" },
  { code: "TOR133", address: "ul. Andersa 145", city: "Toruń", hours: "24/7" },
  { code: "TOR134", address: "ul. Sikorskiego 90", city: "Toruń", hours: "24/7" },
  { code: "TOR135", address: "ul. Maczka 55", city: "Toruń", hours: "24/7" },
  { code: "TOR136", address: "ul. Hallera 33", city: "Toruń", hours: "24/7" },
  { code: "TOR137", address: "ul. Dowbora-Muśnickiego 22", city: "Toruń", hours: "24/7" },
  { code: "TOR138", address: "ul. 11 Listopada 120", city: "Toruń", hours: "24/7" },
  { code: "TOR139", address: "ul. Piłsudskiego 88", city: "Toruń", hours: "24/7" },
  { code: "TOR140", address: "ul. Dworcowa 67", city: "Toruń", hours: "24/7" },
  { code: "TOR141", address: "ul. Pomorska 190", city: "Toruń", hours: "24/7" },
  { code: "TOR142", address: "ul. Kościuszki 145", city: "Toruń", hours: "24/7" },
  { code: "TOR143", address: "ul. Matejki 78", city: "Toruń", hours: "24/7" },
  { code: "TOR144", address: "ul. Mickiewicza 120", city: "Toruń", hours: "24/7" },
  { code: "TOR145", address: "ul. Sienkiewicza 67", city: "Toruń", hours: "24/7" },
  { code: "TOR146", address: "ul. Słowackiego 90", city: "Toruń", hours: "24/7" },
  { code: "TOR147", address: "ul. Krasińskiego 44", city: "Toruń", hours: "24/7" },
  { code: "TOR148", address: "ul. Konopnickiej 19", city: "Toruń", hours: "24/7" },
  { code: "TOR149", address: "ul. Reymonta 55", city: "Toruń", hours: "24/7" },
  { code: "TOR150", address: "ul. Staffa 33", city: "Toruń", hours: "24/7" },
  { code: "TOR151", address: "ul. Tuwima 45", city: "Toruń", hours: "24/7" },
  { code: "TOR152", address: "ul. Gałczyńskiego 78", city: "Toruń", hours: "24/7" },
  { code: "TOR153", address: "ul. Norwida 55", city: "Toruń", hours: "24/7" },
  { code: "TOR154", address: "ul. Asnyka 33", city: "Toruń", hours: "24/7" },
  { code: "TOR155", address: "ul. Fredry 67", city: "Toruń", hours: "24/7" },
  { code: "TOR156", address: "ul. Malczewskiego 19", city: "Toruń", hours: "24/7" },
  { code: "TOR157", address: "ul. Wybickiego 88", city: "Toruń", hours: "24/7" },
  { code: "TOR158", address: "ul. Modrzewiowa 44", city: "Toruń", hours: "24/7" },
  { code: "TOR159", address: "ul. Rekreacyjna 12", city: "Toruń", hours: "24/7" },
  { code: "TOR160", address: "ul. Bajeczna 67", city: "Toruń", hours: "24/7" },
  { code: "TOR161", address: "ul. Czerkaska 22", city: "Toruń", hours: "24/7" },
  { code: "TOR162", address: "ul. Smukalska 78", city: "Toruń", hours: "24/7" },
  { code: "TOR163", address: "ul. Rycerska 55", city: "Toruń", hours: "24/7" },
  { code: "TOR164", address: "ul. Andersa 120", city: "Toruń", hours: "24/7" },
  { code: "TOR165", address: "ul. Sikorskiego 90", city: "Toruń", hours: "24/7" },
  { code: "TOR166", address: "ul. Maczka 33", city: "Toruń", hours: "24/7" },
  { code: "TOR167", address: "ul. Hallera 67", city: "Toruń", hours: "24/7" },
  { code: "TOR168", address: "ul. Dowbora-Muśnickiego 19", city: "Toruń", hours: "24/7" },
  { code: "TOR169", address: "ul. 11 Listopada 145", city: "Toruń", hours: "24/7" },
  { code: "TOR170", address: "ul. Piłsudskiego 88", city: "Toruń", hours: "24/7" },
  { code: "TOR171", address: "ul. Dworcowa 67", city: "Toruń", hours: "24/7" },
  { code: "TOR172", address: "ul. Pomorska 190", city: "Toruń", hours: "24/7" },
  { code: "TOR173", address: "ul. Kościuszki 120", city: "Toruń", hours: "24/7" },
  { code: "TOR174", address: "ul. Matejki 45", city: "Toruń", hours: "24/7" },
  { code: "TOR175", address: "ul. Mickiewicza 105", city: "Toruń", hours: "24/7" },
  { code: "TOR176", address: "ul. Sienkiewicza 78", city: "Toruń", hours: "24/7" },
  { code: "TOR177", address: "ul. Słowackiego 90", city: "Toruń", hours: "24/7" },
  { code: "TOR178", address: "ul. Krasińskiego 44", city: "Toruń", hours: "24/7" },
  { code: "TOR179", address: "ul. Konopnickiej 19", city: "Toruń", hours: "24/7" },
  { code: "TOR180", address: "ul. Reymonta 55", city: "Toruń", hours: "24/7" },
  { code: "TOR181", address: "ul. Staffa 33", city: "Toruń", hours: "24/7" },
  { code: "TOR182", address: "ul. Tuwima 78", city: "Toruń", hours: "24/7" },
  { code: "TOR183", address: "ul. Gałczyńskiego 22", city: "Toruń", hours: "24/7" },
  { code: "TOR184", address: "ul. Norwida 67", city: "Toruń", hours: "24/7" },
  { code: "TOR185", address: "ul. Asnyka 44", city: "Toruń", hours: "24/7" },
  { code: "TOR186", address: "ul. Fredry 19", city: "Toruń", hours: "24/7" },
  { code: "TOR187", address: "ul. Malczewskiego 88", city: "Toruń", hours: "24/7" },
  { code: "TOR188", address: "ul. Wybickiego 55", city: "Toruń", hours: "24/7" },
  { code: "TOR189", address: "ul. Modrzewiowa 33", city: "Toruń", hours: "24/7" },
  { code: "TOR190", address: "ul. Rekreacyjna 67", city: "Toruń", hours: "24/7" },
  { code: "TOR191", address: "ul. Bajeczna 12", city: "Toruń", hours: "24/7" },
  { code: "TOR192", address: "ul. Czerkaska 78", city: "Toruń", hours: "24/7" },
  { code: "TOR193", address: "ul. Smukalska 44", city: "Toruń", hours: "24/7" },
  { code: "TOR194", address: "ul. Rycerska 19", city: "Toruń", hours: "24/7" },
  { code: "TOR195", address: "ul. Andersa 145", city: "Toruń", hours: "24/7" },
  { code: "TOR196", address: "ul. Sikorskiego 90", city: "Toruń", hours: "24/7" },
  { code: "TOR197", address: "ul. Maczka 55", city: "Toruń", hours: "24/7" },
  { code: "TOR198", address: "ul. Hallera 33", city: "Toruń", hours: "24/7" },
  { code: "TOR199", address: "ul. Dowbora-Muśnickiego 22", city: "Toruń", hours: "24/7" },
  { code: "TOR200", address: "ul. 11 Listopada 120", city: "Toruń", hours: "24/7" },
  { code: "TOR201", address: "ul. Piłsudskiego 88", city: "Toruń", hours: "24/7" },
  { code: "TOR202", address: "ul. Dworcowa 67", city: "Toruń", hours: "24/7" },
  { code: "TOR203", address: "ul. Pomorska 190", city: "Toruń", hours: "24/7" },
  { code: "TOR204", address: "ul. Kościuszki 145", city: "Toruń", hours: "24/7" },
  { code: "TOR205", address: "ul. Matejki 78", city: "Toruń", hours: "24/7" },
  { code: "TOR206", address: "ul. Mickiewicza 120", city: "Toruń", hours: "24/7" },
  { code: "TOR207", address: "ul. Sienkiewicza 67", city: "Toruń", hours: "24/7" },
  { code: "TOR208", address: "ul. Słowackiego 90", city: "Toruń", hours: "24/7" },
  { code: "TOR209", address: "ul. Krasińskiego 44", city: "Toruń", hours: "24/7" },
  { code: "TOR210", address: "ul. Konopnickiej 19", city: "Toruń", hours: "24/7" },
  { code: "TOR211", address: "ul. Elbląska 45 (Mokre)", city: "Toruń", hours: "24/7" },
  { code: "TOR212", address: "ul. Wschodnia 78", city: "Toruń", hours: "24/7" },
  { code: "TOR213", address: "ul. Kleeberga 22", city: "Toruń", hours: "24/7" },
  { code: "TOR214", address: "ul. gen. Andersa 67", city: "Toruń", hours: "24/7" },
  { code: "TOR215", address: "ul. gen. Sikorskiego 90", city: "Toruń", hours: "24/7" },
  { code: "TOR216", address: "ul. gen. Maczka 55", city: "Toruń", hours: "24/7" },
  { code: "TOR217", address: "ul. gen. Hallera 33", city: "Toruń", hours: "24/7" },
  { code: "TOR218", address: "ul. gen. Dowbora-Muśnickiego 19", city: "Toruń", hours: "24/7" },
  { code: "TOR219", address: "ul. 11 Listopada 145", city: "Toruń", hours: "24/7" },
  { code: "TOR220", address: "ul. Piłsudskiego 120", city: "Toruń", hours: "24/7" },
  { code: "TOR221", address: "ul. Dworcowa 88", city: "Toruń", hours: "24/7" },
  { code: "TOR222", address: "ul. Pomorska 210", city: "Toruń", hours: "24/7" },
  { code: "TOR223", address: "ul. Kościuszki 145", city: "Toruń", hours: "24/7" },
  { code: "TOR224", address: "ul. Matejki 78", city: "Toruń", hours: "24/7" },
  { code: "TOR225", address: "ul. Mickiewicza 130", city: "Toruń", hours: "24/7" },
  { code: "TOR226", address: "ul. Sienkiewicza 95", city: "Toruń", hours: "24/7" },
  { code: "TOR227", address: "ul. Słowackiego 110", city: "Toruń", hours: "24/7" },
  { code: "TOR228", address: "ul. Krasińskiego 67", city: "Toruń", hours: "24/7" },
  { code: "TOR229", address: "ul. Konopnickiej 44", city: "Toruń", hours: "24/7" },
  { code: "TOR230", address: "ul. Reymonta 78", city: "Toruń", hours: "24/7" },
  { code: "TOR231", address: "ul. Staffa 55", city: "Toruń", hours: "24/7" },
  { code: "TOR232", address: "ul. Tuwima 90", city: "Toruń", hours: "24/7" },
  { code: "TOR233", address: "ul. Gałczyńskiego 67", city: "Toruń", hours: "24/7" },
  { code: "TOR234", address: "ul. Norwida 44", city: "Toruń", hours: "24/7" },
  { code: "TOR235", address: "ul. Asnyka 19", city: "Toruń", hours: "24/7" },
  { code: "TOR236", address: "ul. Fredry 78", city: "Toruń", hours: "24/7" },
  { code: "TOR237", address: "ul. Malczewskiego 55", city: "Toruń", hours: "24/7" },
  { code: "TOR238", address: "ul. Wybickiego 33", city: "Toruń", hours: "24/7" },
  { code: "TOR239", address: "ul. Modrzewiowa 90", city: "Toruń", hours: "24/7" },
  { code: "TOR240", address: "ul. Rekreacyjna 67", city: "Toruń", hours: "24/7" },
  { code: "TOR241", address: "ul. Bajeczna 44", city: "Toruń", hours: "24/7" },
  { code: "TOR242", address: "ul. Czerkaska 19", city: "Toruń", hours: "24/7" },
  { code: "TOR243", address: "ul. Smukalska 78", city: "Toruń", hours: "24/7" },
  { code: "TOR244", address: "ul. Rycerska 55", city: "Toruń", hours: "24/7" },
  { code: "TOR245", address: "ul. Andersa 120", city: "Toruń", hours: "24/7" },
  { code: "TOR246", address: "ul. Sikorskiego 145", city: "Toruń", hours: "24/7" },
  { code: "TOR247", address: "ul. Maczka 90", city: "Toruń", hours: "24/7" },
  { code: "TOR248", address: "ul. Hallera 67", city: "Toruń", hours: "24/7" },
  { code: "TOR249", address: "ul. Dowbora-Muśnickiego 44", city: "Toruń", hours: "24/7" },
  { code: "TOR250", address: "ul. 11 Listopada 120", city: "Toruń", hours: "24/7" },

  // GMINA LUBICZ 
  { code: "LUB001", address: "ul. Toruńska 45 (Lubicz Dolny, przy Biedronce)", city: "Lubicz", hours: "24/7" },
  { code: "LUB002", address: "ul. Główna 12 (Lubicz Górny)", city: "Lubicz", hours: "06:00-22:00" },
  { code: "LUB003", address: "ul. Toruńska 120 (Lubicz Dolny)", city: "Lubicz", hours: "24/7" },
  { code: "LUB004", address: "ul. Sienkiewicza 8 (Lubicz)", city: "Lubicz", hours: "24/7" },
  { code: "LUB005", address: "ul. Bydgoska 67 (Lubicz Górny)", city: "Lubicz", hours: "24/7" },
  { code: "LUB006", address: "ul. Kościelna 15 (Lubicz Dolny)", city: "Lubicz", hours: "06:00-22:00" },
  { code: "LUB007", address: "ul. Sportowa 22 (Lubicz)", city: "Lubicz", hours: "24/7" },
  { code: "LUB008", address: "ul. Toruńska 89 (Lubicz Dolny)", city: "Lubicz", hours: "24/7" },
  { code: "LUB009", address: "ul. Leśna 33 (Lubicz Górny)", city: "Lubicz", hours: "24/7" },
  { code: "LUB010", address: "ul. Polna 18 (Lubicz)", city: "Lubicz", hours: "24/7" },
  { code: "LUB011", address: "ul. Główna 78 (Lubicz Górny)", city: "Lubicz", hours: "24/7" },
  { code: "LUB012", address: "ul. Szkolna 5 (Lubicz Dolny)", city: "Lubicz", hours: "06:00-22:00" },
  { code: "LUB013", address: "ul. Toruńska 200 (Lubicz)", city: "Lubicz", hours: "24/7" },
  { code: "LUB014", address: "ul. Kwiatowa 12 (Lubicz Górny)", city: "Lubicz", hours: "24/7" },
  { code: "LUB015", address: "ul. Parkowa 28 (Lubicz)", city: "Lubicz", hours: "24/7" },

  // GMINA OBROWO 
    { code: "OBR004", address: "ul. Szkolna 5 (Obrowo)", city: "Obrowo", hours: "06:00-22:00" },
  { code: "OBR005", address: "ul. Leśna 22 (Obrowo)", city: "Obrowo", hours: "24/7" },
  { code: "OBR006", address: "ul. Toruńska 120 (Obrowo)", city: "Obrowo", hours: "24/7" },
  { code: "OBR007", address: "ul. Kościelna 8 (Obrowo)", city: "Obrowo", hours: "06:00-22:00" },
  { code: "OBR008", address: "ul. Sportowa 15 (Obrowo)", city: "Obrowo", hours: "24/7" },
  { code: "OBR009", address: "ul. Polna 33 (Obrowo)", city: "Obrowo", hours: "24/7" },
  { code: "OBR010", address: "ul. Główna 89 (Obrowo)", city: "Obrowo", hours: "24/7" },
  { code: "OBR011", address: "ul. Toruńska 200 (Osiedle Obrowo)", city: "Obrowo", hours: "24/7" },
  { code: "OBR012", address: "ul. Kwiatowa 7 (Obrowo)", city: "Obrowo", hours: "24/7" },
  { code: "OBR013", address: "ul. Parkowa 18 (Obrowo)", city: "Obrowo", hours: "24/7" },
  { code: "OBR014", address: "ul. Sienkiewicza 25 (Obrowo)", city: "Obrowo", hours: "24/7" },
  { code: "OBR015", address: "ul. Bydgoska 145", city: "Obrowo", hours: "24/7" },
  { code: "OBR001", address: "ul. Toruńska 45 (Obrowo, przy Lewiatan)", city: "Obrowo", hours: "24/7" },
  { code: "OBR002", address: "ul. Główna 12 (Obrowo)", city: "Obrowo", hours: "06:00-22:00" },
  { code: "OBR003", address: "ul. Bydgoska 78 (Obrowo)", city: "Obrowo", hours: "24/7" },
  { code: "OBR004", address: "ul. Brzozowa 15 (Brzozówka)", city: "Brzozówka", hours: "24/7" },
  { code: "OBR005", address: "ul. Toruńska 112 (Brzozówka)", city: "Brzozówka", hours: "24/7" },
  { code: "OBR006", address: "ul. Dźwierzno 22 (Dźwierzno)", city: "Dźwierzno", hours: "24/7" },
  { code: "OBR007", address: "ul. Główna 8 (Dźwierzno)", city: "Dźwierzno", hours: "06:00-22:00" },
  { code: "OBR009", address: "ul. Łążyn 18 (Łążyn)", city: "Łążyn", hours: "24/7" },
  { code: "OBR010", address: "ul. Toruńska 89 (Łążyn)", city: "Łążyn", hours: "24/7" },
  { code: "OBR011", address: "ul. Dąbska 12 (Nowe Dąbie)", city: "Nowe Dąbie", hours: "24/7" },
  { code: "OBR012", address: "ul. Osiek 25", city: "Osiek", hours: "24/7" },
  { code: "OBR013", address: "ul. Różankowo 7", city: "Różankowo", hours: "24/7" },
  { code: "OBR014", address: "ul. Silno 44", city: "Silno", hours: "24/7" },
  { code: "OBR015", address: "ul. Toruńska 150 (Silno)", city: "Silno", hours: "24/7" },
  { code: "OBR016", address: "ul. Węgorzyn 19", city: "Węgorzyn", hours: "24/7" },
  { code: "OBR017", address: "ul. Złotoryja 28", city: "Złotoryja", hours: "24/7" },
  { code: "OBR018", address: "ul. Toruńska 220 (Obrowo - Osiedle)", city: "Obrowo", hours: "24/7" },
  { code: "OBR019", address: "ul. Leśna 55 (Brzozówka)", city: "Brzozówka", hours: "24/7" },
  { code: "OBR020", address: "ul. Szkolna 10 (Dźwierzno)", city: "Dźwierzno", hours: "06:00-22:00" },

  // GMINA CZERNIKOWO
  { code: "CZE001", address: "ul. Toruńska 67 (Czernikowo, przy Biedronce)", city: "Czernikowo", hours: "24/7" },
  { code: "CZE002", address: "ul. Główna 12 (Czernikowo)", city: "Czernikowo", hours: "06:00-22:00" },
  { code: "CZE003", address: "ul. Bydgoska 45 (Czernikowo)", city: "Czernikowo", hours: "24/7" },
  { code: "CZE004", address: "ul. Szkolna 8 (Czernikowo)", city: "Czernikowo", hours: "06:00-22:00" },
  { code: "CZE005", address: "ul. Toruńska 120 (Czernikowo)", city: "Czernikowo", hours: "24/7" },
  { code: "CZE006", address: "ul. Kościelna 15 (Czernikowo)", city: "Czernikowo", hours: "24/7" },
  { code: "CZE007", address: "ul. Sportowa 22 (Czernikowo)", city: "Czernikowo", hours: "24/7" },
  { code: "CZE008", address: "ul. Polna 33 (Czernikowo)", city: "Czernikowo", hours: "24/7" },
  { code: "CZE009", address: "ul. Leśna 18 (Czernikowo)", city: "Czernikowo", hours: "24/7" },
  { code: "CZE010", address: "ul. Kwiatowa 7 (Czernikowo)", city: "Czernikowo", hours: "24/7" },
  { code: "CZE011", address: "ul. Toruńska 210 (Czernikowo - Osiedle)", city: "Czernikowo", hours: "24/7" },

  // GMINA ZŁAWIEŚ WIELKA 
  { code: "ZLA001", address: "ul. Toruńska 56 (Zławieś Wielka, przy sklepie)", city: "Zławieś Wielka", hours: "24/7" },
  { code: "ZLA002", address: "ul. Główna 15 (Zławieś Wielka)", city: "Zławieś Wielka", hours: "06:00-22:00" },
  { code: "ZLA003", address: "ul. Bydgoska 78 (Zławieś Wielka)", city: "Zławieś Wielka", hours: "24/7" },
  { code: "ZLA004", address: "ul. Szkolna 10 (Zławieś Wielka)", city: "Zławieś Wielka", hours: "06:00-22:00" },
  { code: "ZLA005", address: "ul. Toruńska 145 (Zławieś Wielka)", city: "Zławieś Wielka", hours: "24/7" },
  { code: "ZLA006", address: "ul. Główna 22 (Zławieś Mała)", city: "Zławieś Mała", hours: "24/7" },
  { code: "ZLA007", address: "ul. Toruńska 98 (Zławieś Mała)", city: "Zławieś Mała", hours: "24/7" },
  { code: "ZLA008", address: "ul. Czerniewice 12", city: "Czerniewice", hours: "24/7" },
  { code: "ZLA009", address: "ul. Toruńska 175 (Czerniewice)", city: "Czerniewice", hours: "24/7" },
  { code: "ZLA010", address: "ul. Głuchowo 33", city: "Głuchowo", hours: "24/7" },
  { code: "ZLA011", address: "ul. Główna 8 (Głuchowo)", city: "Głuchowo", hours: "24/7" },
  { code: "ZLA012", address: "ul. Łążyn 25", city: "Łążyn", hours: "24/7" },
  { code: "ZLA013", address: "ul. Sportowa 18 (Zławieś Wielka)", city: "Zławieś Wielka", hours: "24/7" },
  { code: "ZLA014", address: "ul. Leśna 7 (Zławieś Mała)", city: "Zławieś Mała", hours: "24/7" },
  { code: "ZLA015", address: "ul. Polna 44 (Czerniewice)", city: "Czerniewice", hours: "24/7" },
  { code: "ZLA016", address: "ul. Kwiatowa 12 (Zławieś Wielka)", city: "Zławieś Wielka", hours: "24/7" },
  { code: "ZLA017", address: "ul. Parkowa 19 (Zławieś Wielka)", city: "Zławieś Wielka", hours: "24/7" },

  // GMINA ŁUBIANKA 
  { code: "LUB001", address: "ul. Toruńska 34 (Łubianka, przy sklepie)", city: "Łubianka", hours: "24/7" },
  { code: "LUB002", address: "ul. Główna 15 (Łubianka)", city: "Łubianka", hours: "06:00-22:00" },
  { code: "LUB003", address: "ul. Bydgoska 67 (Łubianka)", city: "Łubianka", hours: "24/7" },
  { code: "LUB004", address: "ul. Szkolna 9 (Łubianka)", city: "Łubianka", hours: "06:00-22:00" },
  { code: "LUB005", address: "ul. Toruńska 98 (Łubianka)", city: "Łubianka", hours: "24/7" },
  { code: "LUB006", address: "ul. Brzozowo 12", city: "Brzozowo", hours: "24/7" },
  { code: "LUB007", address: "ul. Toruńska 145 (Brzozowo)", city: "Brzozowo", hours: "24/7" },
  { code: "LUB008", address: "ul. Dąbrowa 22", city: "Dąbrowa Chełmińska", hours: "24/7" },
  { code: "LUB009", address: "ul. Główna 18 (Dąbrowa Chełmińska)", city: "Dąbrowa Chełmińska", hours: "24/7" },
  { code: "LUB010", address: "ul. Łążyn 35", city: "Łążyn", hours: "24/7" },
  { code: "LUB011", address: "ul. Leśna 8 (Łubianka)", city: "Łubianka", hours: "24/7" },
  { code: "LUB012", address: "ul. Sportowa 15 (Łubianka)", city: "Łubianka", hours: "24/7" },
  { code: "LUB013", address: "ul. Polna 28 (Brzozowo)", city: "Brzozowo", hours: "24/7" },
  { code: "LUB014", address: "ul. Kwiatowa 7 (Łubianka)", city: "Łubianka", hours: "24/7" },
  { code: "LUB015", address: "ul. Parkowa 19 (Łubianka)", city: "Łubianka", hours: "24/7" },
  { code: "LUB016", address: "ul. Toruńska 220 (Łubianka)", city: "Łubianka", hours: "24/7" },

  // GMINA ŁYSOMICE 
  { code: "LYS001", address: "ul. Toruńska 56 (Łysomice, przy sklepie)", city: "Łysomice", hours: "24/7" },
  { code: "LYS002", address: "ul. Główna 12 (Łysomice)", city: "Łysomice", hours: "06:00-22:00" },
  { code: "LYS003", address: "ul. Bydgoska 78 (Łysomice)", city: "Łysomice", hours: "24/7" },
  { code: "LYS004", address: "ul. Szkolna 10 (Łysomice)", city: "Łysomice", hours: "06:00-22:00" },
  { code: "LYS005", address: "ul. Toruńska 145 (Łysomice)", city: "Łysomice", hours: "24/7" },
  { code: "LYS006", address: "ul. Sportowa 22 (Łysomice)", city: "Łysomice", hours: "24/7" },
  { code: "LYS007", address: "ul. Turzno 15", city: "Turzno", hours: "24/7" },
  { code: "LYS008", address: "ul. Toruńska 98 (Turzno)", city: "Turzno", hours: "24/7" },
  { code: "LYS009", address: "ul. Gostkowo 25", city: "Gostkowo", hours: "24/7" },
  { code: "LYS010", address: "ul. Główna 18 (Gostkowo)", city: "Gostkowo", hours: "24/7" },
  { code: "LYS011", address: "ul. Różnowo 12", city: "Różnowo", hours: "24/7" },
  { code: "LYS012", address: "ul. Nowa Wieś 33", city: "Nowa Wieś", hours: "24/7" },
  { code: "LYS013", address: "ul. Leśna 8 (Łysomice)", city: "Łysomice", hours: "24/7" },
  { code: "LYS014", address: "ul. Polna 19 (Turzno)", city: "Turzno", hours: "24/7" },
  { code: "LYS015", address: "ul. Kwiatowa 7 (Łysomice)", city: "Łysomice", hours: "24/7" },
  { code: "LYS016", address: "ul. Parkowa 22 (Łysomice)", city: "Łysomice", hours: "24/7" },
  { code: "LYS017", address: "ul. Toruńska 220 (Łysomice)", city: "Łysomice", hours: "24/7" },

  // MIASTO CHEŁMŻA 
   { code: "CHL001", address: "ul. Toruńska 12 (Chełmża, centrum)", city: "Chełmża", hours: "24/7" },
  { code: "CHL002", address: "ul. Rynek 5 (Stare Miasto)", city: "Chełmża", hours: "24/7" },
  { code: "CHL003", address: "ul. 3 Maja 45 (Chełmża)", city: "Chełmża", hours: "24/7" },
  { code: "CHL004", address: "ul. Bydgoska 67 (Chełmża)", city: "Chełmża", hours: "24/7" },
  { code: "CHL005", address: "ul. Szkolna 8 (Chełmża)", city: "Chełmża", hours: "06:00-22:00" },
  { code: "CHL006", address: "ul. Toruńska 120 (Chełmża)", city: "Chełmża", hours: "24/7" },
  { code: "CHL007", address: "ul. Kościuszki 55", city: "Chełmża", hours: "24/7" },
  { code: "CHL008", address: "ul. Mickiewicza 33", city: "Chełmża", hours: "24/7" },
  { code: "CHL009", address: "ul. Piłsudskiego 78", city: "Chełmża", hours: "24/7" },
  { code: "CHL010", address: "ul. Dworcowa 15 (Chełmża)", city: "Chełmża", hours: "24/7" },
  { code: "CHL011", address: "ul. Chełmżyńska 22 (Bielczyny)", city: "Bielczyny", hours: "24/7" },
  { code: "CHL012", address: "ul. Główna 18 (Kłódka)", city: "Kłódka", hours: "24/7" },
  { code: "CHL013", address: "ul. Toruńska 89 (Grzywno)", city: "Grzywno", hours: "24/7" },
  { code: "CHL014", address: "ul. Leśna 7 (Chełmża - okolice)", city: "Chełmża", hours: "24/7" },
  { code: "CHL015", address: "ul. Sportowa 12 (Chełmża)", city: "Chełmża", hours: "24/7" },
  { code: "CHL016", address: "ul. Polna 44 (Chełmża)", city: "Chełmża", hours: "24/7" },
  { code: "CHL017", address: "ul. Kwiatowa 19 (Chełmża)", city: "Chełmża", hours: "24/7" },
  { code: "CHL018", address: "ul. Parkowa 28 (Chełmża)", city: "Chełmża", hours: "24/7" },
  { code: "CHL019", address: "ul. Toruńska 210 (Chełmża)", city: "Chełmża", hours: "24/7" },
  { code: "CHL020", address: "ul. Sienkiewicza 67 (Chełmża)", city: "Chełmża", hours: "24/7" },

  // BYDGOSZCZ
  { code: "BYD001", address: "ul. Gdańska 12 (Centrum)", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD002", address: "ul. Jagiellońska 15", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD003", address: "ul. Fordońska 140 (Lidl, Fordon)", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD004", address: "ul. Nakielska 55 (Biedronka)", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD005", address: "ul. Szubińska 78", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD006", address: "ul. Grunwaldzka 88", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD007", address: "ul. Pomorska 65", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD008", address: "ul. Fordońska 280", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD009", address: "ul. Kromera 67 (Wyżyny)", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD010", address: "ul. Pelplińska 23 (Fordon)", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD011", address: "ul. Nakielska 140 (Błonie)", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD012", address: "ul. Chodkiewicza 45 (Kapuściska)", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD013", address: "ul. Okolna 18 (Okole)", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD014", address: "ul. Leśna 45 (Leśne)", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD015", address: "ul. Bartosza 22 (Bartodzieje)", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD016", address: "ul. Gdańska 45", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD017", address: "ul. 11 Listopada 88", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD018", address: "ul. Wojska Polskiego 12", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD019", address: "ul. Długa 33", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD020", address: "ul. Focha 15", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD021", address: "ul. Kossaka 22", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD022", address: "ul. Sienkiewicza 67", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD023", address: "ul. Mickiewicza 105", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD024", address: "ul. Paderewskiego 48", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD025", address: "ul. Wyzwolenia 19", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD026", address: "ul. Szpitalna 8", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD027", address: "ul. Seminaryjna 12", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD028", address: "ul. Kruszwicka 55", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD029", address: "ul. Toruńska 120", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD030", address: "ul. Inowrocławska 33", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD031", address: "ul. Kapuściska 78", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD032", address: "ul. Tatrzańska 15", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD033", address: "ul. Gdańska 210", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD034", address: "ul. Fordowska 390", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD035", address: "ul. Wyżynna 22", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD036", address: "ul. Bajeczna 8", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD037", address: "ul. Czerkaska 45", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD038", address: "ul. Modrzewiowa 12", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD039", address: "ul. Rekreacyjna 67", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD040", address: "ul. Podgórna 19", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD041", address: "ul. Szarych Szeregów 88", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD042", address: "ul. Smukalska 33", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD043", address: "ul. Rycerska 55", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD044", address: "ul. gen. Andersa 12", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD045", address: "ul. gen. Sikorskiego 78", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD046", address: "ul. gen. Maczka 25", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD047", address: "ul. gen. Hallera 44", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD048", address: "ul. gen. Dowbora-Muśnickiego 19", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD049", address: "ul. 11 Listopada 120", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD050", address: "ul. Piłsudskiego 67", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD051", address: "ul. Dworcowa 88", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD052", address: "ul. Pomorska 210", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD053", address: "ul. Kościuszki 145", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD054", address: "ul. Matejki 22", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD055", address: "ul. Mickiewicza 95", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD056", address: "ul. Sienkiewicza 33", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD057", address: "ul. Słowackiego 78", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD058", address: "ul. Krasińskiego 12", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD059", address: "ul. Konopnickiej 55", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD060", address: "ul. Reymonta 19", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD061", address: "ul. Staffa 44", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD062", address: "ul. Tuwima 28", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD063", address: "ul. Gałczyńskiego 15", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD064", address: "ul. Norwida 33", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD065", address: "ul. Asnyka 22", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD066", address: "ul. Fredry 67", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD067", address: "ul. Malczewskiego 12", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD068", address: "ul. Wybickiego 45", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD069", address: "ul. Modrzewiowa 19", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD070", address: "ul. Rekreacyjna 88", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD071", address: "ul. Modrzewiowa 45", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD072", address: "ul. Rekreacyjna 12", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD073", address: "ul. Bajeczna 67", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD074", address: "ul. Czerkaska 33", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD075", address: "ul. Smukalska 19", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD076", address: "ul. Rycerska 55", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD077", address: "ul. gen. Andersa 120", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD078", address: "ul. gen. Sikorskiego 78", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD079", address: "ul. gen. Maczka 44", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD080", address: "ul. gen. Hallera 22", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD081", address: "ul. gen. Dowbora-Muśnickiego 15", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD082", address: "ul. 11 Listopada 145", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD083", address: "ul. Piłsudskiego 88", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD084", address: "ul. Dworcowa 67", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD085", address: "ul. Pomorska 210", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD086", address: "ul. Kościuszki 120", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD087", address: "ul. Matejki 45", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD088", address: "ul. Mickiewicza 105", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD089", address: "ul. Sienkiewicza 78", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD090", address: "ul. Słowackiego 55", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD091", address: "ul. Krasińskiego 33", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD092", address: "ul. Konopnickiej 19", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD093", address: "ul. Reymonta 67", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD094", address: "ul. Staffa 22", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD095", address: "ul. Tuwima 44", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD096", address: "ul. Gałczyńskiego 12", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD097", address: "ul. Norwida 55", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD098", address: "ul. Asnyka 19", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD099", address: "ul. Fredry 88", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD100", address: "ul. Malczewskiego 33", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD101", address: "ul. Wybickiego 67", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD102", address: "ul. Modrzewiowa 45", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD103", address: "ul. Rekreacyjna 12", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD104", address: "ul. Bajeczna 78", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD105", address: "ul. Czerkaska 22", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD106", address: "ul. Smukalska 55", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD107", address: "ul. Rycerska 19", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD108", address: "ul. Andersa 120", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD109", address: "ul. Sikorskiego 67", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD110", address: "ul. Maczka 44", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD111", address: "ul. Hallera 33", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD112", address: "ul. Dowbora-Muśnickiego 15", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD113", address: "ul. 11 Listopada 88", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD114", address: "ul. Piłsudskiego 145", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD115", address: "ul. Dworcowa 78", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD116", address: "ul. Pomorska 190", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD117", address: "ul. Kościuszki 110", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD118", address: "ul. Matejki 67", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD119", address: "ul. Mickiewicza 88", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD120", address: "ul. Sienkiewicza 55", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD121", address: "ul. Krasińskiego 45", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD122", address: "ul. Konopnickiej 88", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD123", address: "ul. Reymonta 33", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD124", address: "ul. Staffa 67", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD125", address: "ul. Tuwima 19", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD126", address: "ul. Gałczyńskiego 55", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD127", address: "ul. Norwida 22", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD128", address: "ul. Asnyka 78", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD129", address: "ul. Fredry 44", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD130", address: "ul. Malczewskiego 12", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD131", address: "ul. Wybickiego 67", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD132", address: "ul. Modrzewiowa 33", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD133", address: "ul. Rekreacyjna 88", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD134", address: "ul. Bajeczna 19", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD135", address: "ul. Czerkaska 55", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD136", address: "ul. Smukalska 22", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD137", address: "ul. Rycerska 78", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD138", address: "ul. Andersa 145", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD139", address: "ul. Sikorskiego 90", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD140", address: "ul. Maczka 33", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD141", address: "ul. Hallera 67", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD142", address: "ul. Dowbora-Muśnickiego 19", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD143", address: "ul. 11 Listopada 120", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD144", address: "ul. Piłsudskiego 88", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD145", address: "ul. Dworcowa 55", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD146", address: "ul. Pomorska 190", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD147", address: "ul. Kościuszki 145", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD148", address: "ul. Matejki 78", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD149", address: "ul. Mickiewicza 120", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD150", address: "ul. Sienkiewicza 67", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD151", address: "ul. Słowackiego 90", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD152", address: "ul. Krasińskiego 44", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD153", address: "ul. Konopnickiej 19", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD154", address: "ul. Reymonta 55", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD155", address: "ul. Staffa 33", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD156", address: "ul. Tuwima 78", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD157", address: "ul. Gałczyńskiego 22", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD158", address: "ul. Norwida 67", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD159", address: "ul. Asnyka 44", city: "Bydgoszcz", hours: "24/7" },
  { code: "BYD160", address: "ul. Fredry 19", city: "Bydgoszcz", hours: "24/7" },

  // INOWROCŁAW
  { code: "INO001", address: "ul. Toruńska 45 (Inowrocław, centrum)", city: "Inowrocław", hours: "24/7" },
  { code: "INO002", address: "ul. Poznańska 67", city: "Inowrocław", hours: "24/7" },
  { code: "INO003", address: "ul. 3 Maja 12", city: "Inowrocław", hours: "24/7" },
  { code: "INO004", address: "ul. Solna 8 (Solanki)", city: "Inowrocław", hours: "24/7" },
  { code: "INO005", address: "ul. Sienkiewicza 55", city: "Inowrocław", hours: "24/7" },
  { code: "INO006", address: "ul. Bydgoska 78", city: "Inowrocław", hours: "24/7" },
  { code: "INO007", address: "ul. Królowej Jadwigi 33", city: "Inowrocław", hours: "24/7" },
  { code: "INO008", address: "ul. Ratuszowa 15", city: "Inowrocław", hours: "24/7" },
  { code: "INO009", address: "ul. Toruńska 120", city: "Inowrocław", hours: "24/7" },
  { code: "INO010", address: "ul. Sportowa 22", city: "Inowrocław", hours: "24/7" },

  // GRUDZIĄDZ
  { code: "GRU001", address: "ul. Toruńska 34 (Grudziądz)", city: "Grudziądz", hours: "24/7" },
  { code: "GRU002", address: "ul. Rynek 5 (Stare Miasto)", city: "Grudziądz", hours: "24/7" },
  { code: "GRU003", address: "ul. Długa 67", city: "Grudziądz", hours: "24/7" },
  { code: "GRU004", address: "ul. Legionów 12", city: "Grudziądz", hours: "24/7" },
  { code: "GRU005", address: "ul. Bydgoska 89", city: "Grudziądz", hours: "24/7" },
  { code: "GRU006", address: "ul. Piłsudskiego 55", city: "Grudziądz", hours: "24/7" },
  { code: "GRU007", address: "ul. Chełmińska 33", city: "Grudziądz", hours: "24/7" },

  // WŁOCŁAWEK
  { code: "WLO001", address: "ul. Toruńska 78 (Włocławek)", city: "Włocławek", hours: "24/7" },
  { code: "WLO002", address: "ul. Kopernika 12", city: "Włocławek", hours: "24/7" },
  { code: "WLO003", address: "ul. 3 Maja 45", city: "Włocławek", hours: "24/7" },
  { code: "WLO004", address: "ul. Brzezińska 67", city: "Włocławek", hours: "24/7" },
  { code: "WLO005", address: "ul. Piłsudskiego 120", city: "Włocławek", hours: "24/7" },

  // NAKŁO NAD NOTECIĄ
  { code: "NAK001", address: "ul. 11 Listopada 45 (Nakło nad Notecią, centrum)", city: "Nakło nad Notecią", hours: "24/7" },
  { code: "NAK002", address: "ul. Bydgoska 12", city: "Nakło nad Notecią", hours: "24/7" },
  { code: "NAK003", address: "ul. Toruńska 67", city: "Nakło nad Notecią", hours: "24/7" },
  { code: "NAK004", address: "ul. Szkolna 8", city: "Nakło nad Notecią", hours: "06:00-22:00" },
  { code: "NAK005", address: "ul. Piłsudskiego 33", city: "Nakło nad Notecią", hours: "24/7" },
  { code: "NAK006", address: "ul. Kościuszki 19", city: "Nakło nad Notecią", hours: "24/7" },

  // BRODNICA
  { code: "BRO001", address: "ul. Toruńska 56 (Brodnica, centrum)", city: "Brodnica", hours: "24/7" },
  { code: "BRO002", address: "ul. Sądowa 12", city: "Brodnica", hours: "24/7" },
  { code: "BRO003", address: "ul. 3 Maja 45", city: "Brodnica", hours: "24/7" },
  { code: "BRO004", address: "ul. Kościuszki 78", city: "Brodnica", hours: "24/7" },
  { code: "BRO005", address: "ul. Piłsudskiego 33", city: "Brodnica", hours: "24/7" },
  { code: "BRO006", address: "ul. Chełmińska 19", city: "Brodnica", hours: "24/7" },
  { code: "BRO007", address: "ul. Sienkiewicza 55", city: "Brodnica", hours: "24/7" },

  // CHEŁMNO
  { code: "CHM001", address: "ul. Toruńska 34 (Chełmno, centrum)", city: "Chełmno", hours: "24/7" },
  { code: "CHM002", address: "ul. Rynek 5 (Stare Miasto)", city: "Chełmno", hours: "24/7" },
  { code: "CHM003", address: "ul. 3 Maja 67", city: "Chełmno", hours: "24/7" },
  { code: "CHM004", address: "ul. Grudziądzka 12", city: "Chełmno", hours: "24/7" },
  { code: "CHM005", address: "ul. Piłsudskiego 45", city: "Chełmno", hours: "24/7" },
  { code: "CHM006", address: "ul. Kościelna 8", city: "Chełmno", hours: "06:00-22:00" },
  { code: "CHM007", address: "ul. Toruńska 120", city: "Chełmno", hours: "24/7" },

  // TUCHOLA
  { code: "TUC001", address: "ul. Kościuszki 45 (Tuchola, centrum)", city: "Tuchola", hours: "24/7" },
  { code: "TUC002", address: "ul. Główna 12", city: "Tuchola", hours: "24/7" },
  { code: "TUC003", address: "ul. Bydgoska 67", city: "Tuchola", hours: "24/7" },
  { code: "TUC004", address: "ul. Szkolna 8", city: "Tuchola", hours: "06:00-22:00" },
  { code: "TUC005", address: "ul. Piłsudskiego 33", city: "Tuchola", hours: "24/7" },
  { code: "TUC006", address: "ul. Leśna 19", city: "Tuchola", hours: "24/7" },
  { code: "TUC007", address: "ul. Toruńska 89", city: "Tuchola", hours: "24/7" },

  // WARSZAWA
  { code: "WAW001", address: "ul. Marszałkowska 104/106 (Centrum)", city: "Warszawa", hours: "24/7" },
  { code: "WAW002", address: "ul. Świętokrzyska 30", city: "Warszawa", hours: "24/7" },
  { code: "WAW003", address: "ul. Aleje Jerozolimskie 125", city: "Warszawa", hours: "24/7" },
  { code: "WAW004", address: "ul. Puławska 145 (Mokotów)", city: "Warszawa", hours: "24/7" },
  { code: "WAW005", address: "ul. Górczewska 212 (Bemowo)", city: "Warszawa", hours: "24/7" },
  { code: "WAW006", address: "ul. Bielańska 12 (Stare Miasto)", city: "Warszawa", hours: "24/7" },

  // KRAKÓW
  { code: "KRK001", address: "ul. Floriańska 15 (Stare Miasto)", city: "Kraków", hours: "24/7" },
  { code: "KRK002", address: "ul. Wielicka 259 (Podgórze)", city: "Kraków", hours: "24/7" },
  { code: "KRK003", address: "ul. Zakopiańska 62", city: "Kraków", hours: "24/7" },
  { code: "KRK004", address: "ul. Bora-Komorowskiego 25 (Nowa Huta)", city: "Kraków", hours: "24/7" },
  { code: "KRK005", address: "ul. Mogilska 83", city: "Kraków", hours: "24/7" },

  // POZNAŃ 
  { code: "POZ001", address: "ul. Półwiejska 27 (Stare Miasto)", city: "Poznań", hours: "24/7" },
  { code: "POZ002", address: "ul. Głogowska 416 (Grunwald)", city: "Poznań", hours: "24/7" },
  { code: "POZ003", address: "ul. Hetmańska 33", city: "Poznań", hours: "24/7" },
  { code: "POZ004", address: "ul. Winogrady 178", city: "Poznań", hours: "24/7" },
  { code: "POZ005", address: "ul. Marcelińska 90", city: "Poznań", hours: "24/7" },

  // WROCŁAW 
  { code: "WRO001", address: "ul. Świdnicka 15 (Centrum)", city: "Wrocław", hours: "24/7" },
  { code: "WRO002", address: "ul. Legnicka 58", city: "Wrocław", hours: "24/7" },
  { code: "WRO003", address: "ul. Aleja Kromera 15 (Krzyki)", city: "Wrocław", hours: "24/7" },
  { code: "WRO004", address: "ul. Grabiszyńska 241", city: "Wrocław", hours: "24/7" },

  // GDAŃSK 
  { code: "GDA001", address: "ul. Długa 41 (Główne Miasto)", city: "Gdańsk", hours: "24/7" },
  { code: "GDA002", address: "ul. Grunwaldzka 211 (Wrzeszcz)", city: "Gdańsk", hours: "24/7" },
  { code: "GDA003", address: "ul. Subisława 20 (Oliwa)", city: "Gdańsk", hours: "24/7" },

  // ŁÓDŹ 
  { code: "LDZ001", address: "ul. Piotrkowska 87", city: "Łódź", hours: "24/7" },
  { code: "LDZ002", address: "ul. Pabianicka 92", city: "Łódź", hours: "24/7" },
  { code: "LDZ003", address: "ul. Aleksandrowska 122", city: "Łódź", hours: "24/7" },

  // KATOWICE 
  { code: "KAT001", address: "ul. Mariacka 20", city: "Katowice", hours: "24/7" },
  { code: "KAT002", address: "ul. Korfantego 51", city: "Katowice", hours: "24/7" },
  { code: "KAT003", address: "ul. Chorzowska 107", city: "Katowice", hours: "24/7" },

  // LUBLIN 
  { code: "LUB001", address: "ul. Krakowskie Przedmieście 45", city: "Lublin", hours: "24/7" },
  { code: "LUB002", address: "ul. 3 Maja 18", city: "Lublin", hours: "24/7" },

  // SZCZECIN 
  { code: "SZE001", address: "ul. Wojska Polskiego 45", city: "Szczecin", hours: "24/7" },
  { code: "SZE002", address: "ul. Aleja Piastów 65", city: "Szczecin", hours: "24/7" },
];