import { Product } from "./types";

export const products: Product[] = [
  {
    id: 1,
    name: "Miód rzepakowy",
    description: "Jasnozłoty, bardzo słodki i delikatny. Szybko krystalizuje w drobną, kremową konsystencję.",
    longDescription: "Miód rzepakowy to jeden z najjaśniejszych polskich miodów. Charakteryzuje się bardzo słodkim, delikatnym smakiem z nutą kwiatową. Szybko krystalizuje, tworząc drobną, kremową konsystencję. Idealny do herbaty, kanapek, naleśników i dla dzieci. Pochodzi z obfitych pożytków rzepakowych na kujawskich polach.",
    price: 60,
    unit: "słoik 900 g",
    category: "miody",
    image: "https://images.unsplash.com/photo-1608797178974-15b35a64ede9?w=800&q=80",
    inStock: 42,
  },
  {
    id: 2,
    name: "Miód rzepakowy",
    description: "Jasnozłoty, bardzo słodki i delikatny. Szybko krystalizuje w drobną, kremową konsystencję.",
    longDescription: "Miód rzepakowy to jeden z najjaśniejszych polskich miodów. Charakteryzuje się bardzo słodkim, delikatnym smakiem z nutą kwiatową. Szybko krystalizuje, tworząc drobną, kremową konsystencję. Idealny do herbaty, kanapek, naleśników i dla dzieci. Pochodzi z obfitych pożytków rzepakowych na kujawskich polach.",
    price: 30,
    unit: "słoik 350 g",
    category: "miody",
    image: "https://images.unsplash.com/photo-1608797178974-15b35a64ede9?w=800&q=80",
    inStock: 35,
  },
  {
    id: 3,
    name: "Miód lipowy",
    description: "Intensywny, mentolowy, z wyraźnym aromatem kwitnącej lipy. Działa uspokajająco i wspiera odporność.",
    longDescription: "Miód lipowy pozyskiwany z nektaru kwiatów lipy. Posiada intensywny, korzenno-mentolowy aromat i delikatnie rozgrzewający smak. Tradycyjnie stosowany przy przeziębieniach, problemach z gardłem oraz jako naturalny środek uspokajający. Pochodzi z pięknych, starych lip rosnących wzdłuż Wisły i na terenach nadwiślańskich.",
    price: 60,
    unit: "słoik 900 g",
    category: "miody",
    image: "https://images.unsplash.com/photo-1587049352851-8d4e8912c8f8?w=800&q=80",
    inStock: 28,
  },
  {
    id: 4,
    name: "Miód wielokwiatowy",
    description: "Delikatny, kwiatowy, o przyjemnym i złożonym smaku. Najbardziej uniwersalny miód na co dzień.",
    longDescription: "Miód zbierany z bogatej, zróżnicowanej bazy pożytkowej terenów nadwiślańskich Kujaw — łąk, zadrzewień i ogrodów. Delikatny, zrównoważony smak z nutami wielu kwiatów. Najlepszy wybór na co dzień: do herbaty, kanapek, deserów i dla całej rodziny. Bogaty w naturalne enzymy i mikroelementy.",
    price: 60,
    unit: "słoik 900 g",
    category: "miody",
    image: "https://images.unsplash.com/photo-1502741126161-b048400d0859?w=800&q=80",
    inStock: 51,
  },
  {
    id: 5,
    name: "Miód wielokwiatowy",
    description: "Delikatny, kwiatowy, o przyjemnym i złożonym smaku. Najbardziej uniwersalny miód na co dzień.",
    longDescription: "Miód zbierany z bogatej, zróżnicowanej bazy pożytkowej terenów nadwiślańskich Kujaw — łąk, zadrzewień i ogrodów. Delikatny, zrównoważony smak z nutami wielu kwiatów. Najlepszy wybór na co dzień: do herbaty, kanapek, deserów i dla całej rodziny. Bogaty w naturalne enzymy i mikroelementy.",
    price: 30,
    unit: "słoik 350 g",
    category: "miody",
    image: "https://images.unsplash.com/photo-1502741126161-b048400d0859?w=800&q=80",
    inStock: 29,
  },
  {
    id: 6,
    name: "Miód gryczany",
    description: "Ciemny, intensywny, lekko pikantny i gorzki. Bogaty w rutynę i antyoksydanty. Doskonały na wzmocnienie.",
    longDescription: "Miód gryczany o głębokiej, ciemnej barwie i charakterystycznym, intensywnym smaku z lekką goryczką. Bardzo bogaty w rutynę, żelazo i antyoksydanty. Tradycyjnie polecany przy anemii, problemach z krążeniem i jako naturalne wsparcie odporności. Idealny do mięs, sosów, pierników i jako dodatek do diety wzmacniającej.",
    price: 60,
    unit: "słoik 900 g",
    category: "miody",
    image: "https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=800&q=80",
    inStock: 24,
  },
  {
    id: 7,
    name: "Miód akacjowy",
    description: "Jeden z najjaśniejszych i najdelikatniejszych miodów. Subtelny kwiatowy zapach, bardzo wolno krystalizuje.",
    longDescription: "Miód akacjowy z robinii akacjowej — jeden z najdelikatniejszych i najjaśniejszych miodów. Subtelny, kwiatowy aromat, bardzo łagodny smak. Krystalizuje niezwykle wolno, przez wiele miesięcy zachowując płynną konsystencję. Idealny do herbaty, deserów, naleśników i dla osób ceniących łagodne smaki. Polecany także dla dzieci.",
    price: 60,
    unit: "słoik 900 g",
    category: "miody",
    image: "https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=800&q=80",
    inStock: 19,
  },
  {
    id: 8,
    name: "Miód akacjowy",
    description: "Jeden z najjaśniejszych i najdelikatniejszych miodów. Subtelny kwiatowy zapach, bardzo wolno krystalizuje.",
    longDescription: "Miód akacjowy z robinii akacjowej — jeden z najdelikatniejszych i najjaśniejszych miodów. Subtelny, kwiatowy aromat, bardzo łagodny smak. Krystalizuje niezwykle wolno, przez wiele miesięcy zachowując płynną konsystencję. Idealny do herbaty, deserów, naleśników i dla osób ceniących łagodne smaki. Polecany także dla dzieci.",
    price: 30,
    unit: "słoik 350 g",
    category: "miody",
    image: "https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=800&q=80",
    inStock: 22,
  },
  {
    id: 9,
    name: "Miód akacjowo-spadzowy",
    description: "Połączenie delikatności akacji z żywiczną głębią spadzi. Wyjątkowy, złożony bukiet smakowy.",
    longDescription: "Rzadki i ceniony miód powstały z połączenia nektaru akacji oraz spadzi. Łączy w sobie delikatność i subtelność akacji z głębokim, żywicznym aromatem spadzi. Posiada wyjątkowy, złożony bukiet smakowy. Pochodzi z terenów bogatych w akacje i lasy nadwiślańskie. Dostępny w ograniczonej ilości.",
    price: 60,
    unit: "słoik 900 g",
    category: "miody",
    image: "https://images.unsplash.com/photo-1471943311424-646960669fbc?w=800&q=80",
    inStock: 15,
  },
  {
    id: 10,
    name: "Miód nawłociowy",
    description: "Złocisto-żółty, o intensywnym ziołowym aromacie. Późnoletni miód wspierający odporność.",
    longDescription: "Miód pozyskiwany późnym latem i jesienią z nektaru nawłoci pospolitej. Charakteryzuje się piękną, złocistą barwą i intensywnym, ziołowo-kwiatowym aromatem. Wspiera naturalną odporność organizmu. Pochodzi z bogatych, dzikich łąk i zadrzewień nad Wisłą. Dostępny od września do grudnia.",
    price: 60,
    unit: "słoik 900 g",
    category: "miody",
    image: "https://images.unsplash.com/photo-1609505848912-b7c3c6f5f3e3?w=800&q=80",
    inStock: 18,
  },
  {
    id: 11,
    name: "Pyłek pszczeli",
    description: "Naturalny superfood. Bogaty w białko, witaminy, minerały i antyoksydanty.",
    longDescription: "Świeżo suszony pyłek kwiatowy zbierany przez nasze pszczoły na kujawskich łąkach i zadrzewieniach. Jedno z najbardziej wartościowych naturalnych źródeł białka roślinnego, witamin z grupy B, żelaza, cynku i antyoksydantów. Zalecany przy osłabieniu, rekonwalescencji, w okresach zwiększonego wysiłku oraz jako codzienne wsparcie odporności i witalności.",
    price: 38,
    unit: "słoik 200 g",
    category: "produkty",
    image: "https://images.unsplash.com/photo-1599599810769-b8a4c1c1c1c1?w=800&q=80",
    inStock: 26,
  },
  {
    id: 12,
    name: "Plastry miodu",
    description: "Naturalny miód w plastrze – prosto z ula. Najczystsza, najbardziej pierwotna forma miodu.",
    longDescription: "Piękne, pełne plastry miodu prosto z naszych uli. Miód w naturalnym woskowym plastrze – bez wirowania i obróbki. Najczystsza i najbardziej tradycyjna forma spożycia miodu. Można jeść razem z woskiem (wosk jest jadalny i bogaty w propolis). Idealny na deser, do herbaty lub jako wyjątkowy, naturalny przysmak. Waga ok. 450–500 g.",
    price: 55,
    unit: "plaster ok. 450–500 g",
    category: "produkty",
    image: "https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=800&q=80",
    inStock: 12,
  },
  {
    id: 13,
    name: "Świece z wosku pszczelego",
    description: "Naturalne świece 100% z wosku pszczelego. Czyste spalanie i delikatny miodowy zapach.",
    longDescription: "Ręcznie wytwarzane świece ze 100% czystego wosku pszczelego pozyskanego w naszej pasiece. Bez parafiny, stearyny i sztucznych dodatków. Palą się równo, czysto, nie kopcą i wydzielają subtelny, naturalny zapach miodu i wosku. Tworzą przyjemną, ciepłą atmosferę. Świece mniejsze (ok. 150 g) oraz większe (od 45 zł).",
    price: 32,
    unit: "150 g",
    category: "produkty",
    image: "https://images.unsplash.com/photo-1602874801006-5c5f4a5e4f1c?w=800&q=80",
    inStock: 31,
  },
];
